### ISSUE TITLE
miniplayer / smallplayer

### ISSUE THREAD

**Issue by wahabah** [veertly/app#144]
Thanks for the awesome work!!!
trying to figure out how to have the small player enabled for main stage... or what conditions are applied on that.. ?
could you guide where to enable mini player from?

also, i just installed telegram, was trying to add the creator but i think it does ask for a phone number to add from? or does it allow to add from username too? sorry haven't really used telegram in a while now..

**Comment by Fahad-pnw** [comment]
following thread.

**Comment by joaoaguiam** [comment]
Hi wahabah, thanks for your message! The mini-player needs to be activated for each event using the collection enabled features.

you can join our telegram here: https://t.me/veertly  or get in touch with me on twitter: https://twitter.com/joaoaguiam or https://twitter.com/veertly . Just ping us and we can schedule a call :)

**Comment by Fahad-pnw** [comment]
thank you for your prompt response. 

trying to figure out in firestore as well as in the code. 
something like SET_ENABLED_FEATURES to true?

in code, if we want to always keep the features/miniplayer enabled, anything to guide us would be helpful.

Thanks again for the awesome work!!!

**Comment by joaoaguiam** [comment]
Hey, to have the small player always enabled, you can set this const to true: https://github.com/veertly/app/blob/f72dea1942ead187b426dd3c0c7844785ebc6760/src/Contexts/SmallPlayerContext.js#L50
