### ISSUE TITLE
Unable to see advanced configuration in Rooms as in the demo

### ISSUE THREAD

**Issue by sangeetjass** [veertly/app#157]
Dear Team,
We are unable to see the amazing advanced configuration while creating rooms, do we need to enable that from somewhere?

**Comment by sangeetjass** [comment]
Basically add app feature is missing

**Comment by joaoaguiam** [comment]
Hello @sangeetjass, Indeed, the custom rooms is a premium feature and we are not providing it on the open source version. If you want to know more about our premium features just let me know. We also have a full white-label solution to offer to our partners.

**Comment by sangeetjass** [comment]
> Hello @sangeetjass, Indeed, the custom rooms is a premium feature and we are not providing it on the open source version. If you want to know more about our premium features just let me know. We also have a full white-label solution to offer to our partners.

Hi Joaoguiam, can we arrange a quick demo of the white-label solution?  I would love to explore that for India and UAE market.

**Comment by joaoaguiam** [comment]
Hi @sangeetjass sorry for the delay but I completely missed your message. Just ping me on telegram, more than happy to share it with you: https://t.me/joaoaguiam
