### ISSUE TITLE
Cockpit source code 

### ISSUE THREAD

**Issue by bernardnongpoh** [veertly/app#160]
Hello Veertly Developers, Thanks for such a wonderful product. I am able to setup in my firebase account as quick as 30 mins. I would like to know regarding the cockpit feature. Is is available or it for premium users.

**Comment by harish-aka-shivi** [comment]
Hi @bernardnongpoh. Yes, the Cockpit is for premium users. Feel free to contact @joaoaguiam to more about it.
Cheers.

**Comment by bernardnongpoh** [comment]
Thanks

**Comment by joaoaguiam** [comment]
Hi @bernardnongpoh , Feel free to reach to us on https://t.me/veertly or directly with me at https://t.me/joaoaguiam Happy to share more insights!
