### ISSUE TITLE
Chat pane is not scrollable

### ISSUE THREAD

**Issue by harish-aka-shivi** [veertly/app#33]
## Description
Thanks for the awesome app. I am trying to set it up for using it and also hoping to contribute to it. The one issue I faced is that the messages in the chat pane area are not scrollable. 

## Environment
Browser: Firefox
OS: macOS

**Comment by harish-aka-shivi** [comment]
Currently I am looking into it.

**Comment by joaoaguiam** [comment]
Thanks a lot for fixing it! Deployed in production :)
